version: '3.1'

services:

    postgres-12:
        # context: .
        image: postgres:12-alpine
        restart: always
        ports:
            - "50000:5432"
        environment: 
            POSTGRES_PASSWORD: docker
